### ISSUE TITLE
Use of Concourse fonts

### ISSUE THREAD

**Issue by mbutterick** [bensk/bensk.github.io#2]
I notice that you’re using my copyrighted Concourse fonts [on your website](http://bsk.education/cs_lessons/FinalProject/), and also redistributing them through this repo. 

1) Have you paid for them? I’m afraid I can’t find your name in my customer database.

2) Whether you’ve paid for them or not, you can’t put them in a public repo. Sorry.

**Comment by bensk** [comment]
Shoot, I am so sorry. It was a test with my students and I’ll take it down.
